general:
  root_path: /home/koenig/alpha-beta-CROWN
  csv_name: mnist_instances__mnist_cnn_a_adv.csv
data:
  start: 25125
  end: 50000
  dataset: MNIST_SDP
attack:
  pgd_restarts: 50
solver:
  batch_size: 512 # 1024
  beta-crown:
    iteration: 20 # 20
    lr_beta: 0.005 # 0.05
bab:
  timeout: 3600 # 180
  branching:
    reduceop: max
  cut:
    enabled: True
    cplex_cuts: True
    bab_cut: True
    lr_decay: 0.9
