general:
  root_path: /home/koenig/alpha-beta-CROWN
  csv_name: mnist_instances__eran_mlp.csv
  complete_verifier: bab-refine
model:
  onnx_optimization_flags: remove_ineffective_layers, remove_relu_in_last_layer
data:
  dataset: MNIST
solver:
  batch_size: 500
  beta-crown:
    iteration: 20
  mip:
    parallel_solvers: 16
    refine_neuron_time_percentage: 0.8
