# Configuration file for running the cifar2020 benchmark (all properties).
general:
  root_path: /home/koenig/alpha-beta-CROWN
  csv_name: cifar_instances__cifar2020_2_255.csv
data:
  dataset: CIFAR
solver:
  batch_size: 200
  beta-crown:
    lr_beta: 0.01
bab:
  branching:
    reduceop: max
    candidates: 10
  initial_max_domains: 10
attack:
  pgd_order: middle
