# Configuration file for running the oval21 benchmark (all properties).
general:
  root_path: /home/koenig/alpha-beta-CROWN
  csv_name: cifar_instances__oval22.csv
  conv_mode: matrix
data:
  start: 0
  end: 30000
  dataset: CIFAR
solver:
  batch_size: 2000
  beta-crown:
    lr_beta: 0.01
  start_save_best: -1
  prune_after_crown: False
bab:
  branching:
    reduceop: max
    candidates: 10
  cut:
    enabled: True
    cplex_cuts: True
    bab_cut: True
    lr_beta: 0.01
attack:
  pgd_order: middle
